# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'octokit'     # GitHub API wrapper
gem 'thor'        # CLI framework
gem 'dotenv'
gem "tty-prompt"
gem "pastel"
gem 'faraday-retry'
